# Base configs
baseurl: "http://photography.phongvu.dev"

image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "phongvufoto"
subtitle: "See the world through my eyes!"
author: "Phong Vu"
bio: "Just a software developer with passion with photography."
publicise: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/phong.vu.758"
  twitter: "https://www.twitter.com/Phong_Vu"
  instagram: "https://www.instagram.com/phongvufoto"
  linkedin: "https://in.linkedin.com/in/phong-vu-software-developer"
  github: "https://www.github.com/phongvu2508"
